#    ,---.                                  ,--.
#   /  O  \,--.  ,--.,---.  ,---. ,--,--. ,-|  | ,---.
#  |  .-.  |\  `'  /| .-. || .--'' ,-.  |' .-. || .-. |
#  |  | |  | \    / ' '-' '\ `--.\ '-'  |\ `-' |' '-' '
#  `--' `--'  `--'   `---'  `---' `--`--' `---'  `---'
# Almost all the things in the website can be customized from here.
# Changing title and description according to your website requirement is important.
#
title: Kapitalisman
description: Blog over het opbouwen en behouden van vermogen
disclaimer: Ik ben geen financieel adviseur. De teksten op mijn website zijn uitsluitend ter lering en vermaak. Ik schrijf vanuit mijn eigen ervaring en gebaseerd op mijn eigen onderzoek.
copyright: ©
email: kapitalisman@protonmail.com # The contact form submission will be done to this email address.
phone: +31-6-1234-9999
url: https://kapitalisman.nl
default-image: /assets/images/logo/logo-transparant.png # This image will be shown on sharing any page on social media. For example: Homepage, about page etc. This image should be bigger than 200x200px. This image is not used for posts. Posts use their own image mentioned in individual posts.

# Author details shows up at the end of every article
author:
  name: Sam
  bio: "Blog over het opbouwen en behouden van vermogen."
  image: author-image.png # Choose a 200x200px image and place it inside /images directory.
  instagram: https://instagram.com/kapitalisman
  twitter: https://twitter.com/kapitalisman

# Kramdown is supported by Github
markdown: kramdown

# Mathjax setting
enable-mathjax: yes

# Charts
enable-chartjs: yes

# This defines how the URLs should look like
permalink: /blog/:title/

# Pagination - Posts per page in the blog index
paginate: 4
paginate_path: /blog/page:num/

# Define titles for the sections
name: Kapitalisman
projects: Website

# Jekyll will read contents inside _pages only if we tell it to
include:
  - _pages

# Google Ananlytics Tracker
analytics: UA-189279720-1 # Sign up with Google analytics and replce with your analytics ID

# Tidio chat script
# Signup with tidio.com and navigate to https://www.tidio.com/panel/channels/widget/integration to find your chat script
# tidio-chat-script: '<script src="//code.tidio.co/atcbwe5jq0ftiidebmmfwybic3nagfnf.js" async></script>'

# Share buttons
share: yes # Change it to `no` to remove share buttons.

# Comments by Disqus # Sign up with Disqus to get your shortcode. Leave it blank if you do not want to run diqus code on the website.
disqus: kapitalisman

#
#   ,-----.                                                    ,--.
#  '  .--./ ,---. ,--,--,--. ,---. ,--.--. ,---.  ,---.  ,---. `--' ,---. ,--,--,
#  |  |    | .-. ||        || .-. ||  .--'| .-. :(  .-' (  .-' ,--.| .-. ||      \
#  '  '--'\' '-' '|  |  |  || '-' '|  |   \   --..-'  `).-'  `)|  |' '-' '|  ||  |
#   `-----' `---' `--`--`--'|  |-' `--'    `----'`----' `----' `--' `---' `--''--'
#                           `--'
# All compression variables are declared here.

sass:
  sass_dir: /assets/css/_sass
  style: compressed

#compress.html
compress_html:
  clippings: [html, head, meta, title, link, body, div, script, header, footer]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

####################################################################################################

destination: _site

exclude:
  - .git

# These plugins are supported by github by default and can be installed locally using ruby gems
plugins:
  - jekyll-sitemap # Adds sitemap to the website at /sitemap.xml
  - jekyll-feed # Adds feed to the website at /feed.xml
  - jekyll-paginate # Used for sorting posts by page numbers.
  - jekyll-seo-tag # Adds all the important SEO meta tags by default.
  - jemoji

emoji:
  src: "https://github.githubassets.com/images/icons/"
